Indentation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,7 +41,7 @@ jobs:
     # Construct the correct docker container image tag corresponding to this branch/pull
     - name: Figure out correct docker image tag
       run:
-          echo ::set-env name=DOCKER_IMG::$DOCKER_BASE_IMG:$(git log -1 --oneline -- tools/docker/ | cut -d" " -f1)
+        echo ::set-env name=DOCKER_IMG::$DOCKER_BASE_IMG:$(git log -1 --oneline -- tools/docker/ | cut -d" " -f1)
 
     # Try to download the image from dockerhub. If it works, use it.
     #
@@ -55,18 +55,18 @@ jobs:
     # contiki-ng/contiki-ng, not for builds on forks.
     - name: Try to download image from dockerhub
       run: |
-          echo "Using $DOCKER_IMG for this run"
-          echo "Pulling image $DOCKER_IMG from dockerhub";
-          docker pull $DOCKER_IMG
-          echo ::set-env name=DOCKER_NEED_BUILD::$?
+        echo "Using $DOCKER_IMG for this run"
+        echo "Pulling image $DOCKER_IMG from dockerhub";
+        docker pull $DOCKER_IMG
+        echo ::set-env name=DOCKER_NEED_BUILD::$?
 
     - name: Build docker image if required
       if: env.DOCKER_NEED_BUILD != '0'
       run: |
-          echo $DOCKER_IMG "does not exist or pull failed"
-          echo "This is normal for PR builds and for builds on forks"
-          echo "Building from dockerfile"
-          docker build tools/docker -t $DOCKER_IMG
+        echo $DOCKER_IMG "does not exist or pull failed"
+        echo "This is normal for PR builds and for builds on forks"
+        echo "Building from dockerfile"
+        docker build tools/docker -t $DOCKER_IMG
 
     - name: Push image to dockerhub
       #if: github.repository == 'contiki-ng/contiki-ng' && github.event == 'pull_request'
@@ -75,8 +75,8 @@ jobs:
         echo "This is a branch build that updates the container. Push image to Dockerhub"
         echo ${{ github.repository }}
         echo ${{ github.event_name }}
-        echo ${{ github.event }}
         echo ${{ github.event.action }}
+        echo ${{ github.pull_request.merged }}
         #echo $DOCKERHUB_PASSWD | docker login --username contiker --password-stdin
         #docker push $DOCKER_IMG;
 
@@ -85,28 +85,31 @@ jobs:
     # If this was a merge on master or develop then push to dockerhub an
     # additional tag
     - name: Push additional tag to dockerhub for master/develop
-      if: env.DOCKER_NEED_PUSH == '1' && (github.ref == 'master' || github.ref == 'develop') 
+      #if: env.DOCKER_NEED_PUSH == '1' && (github.ref == 'master' || github.ref == 'develop')
       run: |
         echo This is a merge in branch ${{ github.ref }}
         echo Push also $DOCKER_BASE_IMG:${{ github.ref }}
-        docker tag $DOCKER_IMG $DOCKER_BASE_IMG:${{ github.ref }}
+        #docker tag $DOCKER_IMG $DOCKER_BASE_IMG:${{ github.ref }}
         #docker push $DOCKER_BASE_IMG:${{ github.ref }}
+        echo ${{ github.ref }}
+        echo env.DOCKER_NEED_PUSH
+
 
     # Clone the repo used for out-of-tree builds if required
     - name: Clone the repo used for out-of-tree builds if required
       if: matrix.test == 'Builds'
       run: |
-          mkdir -p $OUT_OF_TREE_TEST_PATH
-          git clone --depth 1 https://github.com/contiki-ng/out-of-tree-tests $OUT_OF_TREE_TEST_PATH
-          cd $OUT_OF_TREE_TEST_PATH
-          git checkout $OUT_OF_TREE_TEST_VER
+        mkdir -p $OUT_OF_TREE_TEST_PATH
+        git clone --depth 1 https://github.com/contiki-ng/out-of-tree-tests $OUT_OF_TREE_TEST_PATH
+        cd $OUT_OF_TREE_TEST_PATH
+        git checkout $OUT_OF_TREE_TEST_VER
 
     # Fire up the container and run corresponding tests
     - name: Execute tests
       run: |
-           'printf "\n\n>>>>> Running suite: $TEST_NAME ($TESTS) <<<<<\n"'
-           #for TEST in $TESTS; do printf "\n\n--- Running test $TEST:\n"; docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v $OUT_OF_TREE_TEST_PATH:/home/user/out-of-tree-tests -v $CNG_HOST_PATH:/home/user/contiki-ng -ti $DOCKER_IMG bash --login -c "make -C tests/??-$TEST"; done
-           'printf "\n\n>>>>>> Checking all tests <<<<<\n"'
-           RET=0
-           #for TEST in $TESTS; do $CNG_HOST_PATH/tests/check-test.sh $CNG_HOST_PATH/tests/??-$TEST || RET=1; done
-           #exit $RET
+        'printf "\n\n>>>>> Running suite: $TEST_NAME ($TESTS) <<<<<\n"'
+        #for TEST in $TESTS; do printf "\n\n--- Running test $TEST:\n"; docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v $OUT_OF_TREE_TEST_PATH:/home/user/out-of-tree-tests -v $CNG_HOST_PATH:/home/user/contiki-ng -ti $DOCKER_IMG bash --login -c "make -C tests/??-$TEST"; done
+        'printf "\n\n>>>>>> Checking all tests <<<<<\n"'
+        RET=0
+        #for TEST in $TESTS; do $CNG_HOST_PATH/tests/check-test.sh $CNG_HOST_PATH/tests/??-$TEST || RET=1; done
+        #exit $RET
